# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de9c5a0a5d43c43d34783a10e55619859bd696ae1acd64f09152978db92e7fbbc71a0b24ae8fa6073fbca2ac024aa190b084bc6757f564ee4c98c1f07ea6d91

test:
  secret_key_base: 98c03eb3316191df95bd5b062a838db8d413aae1184f6e334567327b67383169b85dae9d2f59f46e62b4e44b6b724c53d4b9f58928a70bd1588ff36b7e204e1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
